---
title: "1222_practice"
author: "Shih"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 考古題: 第一題


```{r}
set.seed(12345)
(number <- sample(1:1000, sample(500:600,1), replace=T))

# 找出可以被7整除的数字的位置
location7 <- which(number %% 7 == 0)

# 列出结果
list(location7 = location7)

div7 <- number[number %% 7 == 0]
sixty7 <- div7[60]
list(sixty7 = sixty7)
```

## 考古題: 第二題


```{r}
# 設定種子和生成資料
set.seed(123)
n <- 26
records <- round(runif(n, 9.5, 12.3), 1)

# 建立年份序列（從2000開始的26年）
years <- 2000:(2000+n-1)

# 計算至各年度的最小值記錄
histmin <- sapply(1:n, function(i) min(records[1:i]))

# 判斷是否等於歷史最小值
breakeven <- records == histmin

# 判斷是否破記錄
# 注意：需要特別處理第一個值，因為它沒有之前的記錄可比較
breakif <- c(TRUE, sapply(2:n, function(i) {
    records[i] < min(records[1:(i-1)])
}))

# 建立 data.frame
result <- data.frame(
    year = years,
    histmin = histmin,
    breakeven = breakeven,
    breakif = breakif
)

# 將年份設為 row names
rownames(result) <- years



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
